apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
      - name: restapi-container
        image: priya123456/restapi
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: restapi-service
spec:
  type: NodePort
  selector:
    app: restapi
  ports:
  - port: 7000
    targetPort: 7000
    nodePort: 30007
